"""
Django settings for sushi_delivery_shop project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Путь к корневой директории проекта
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Ключ безопасности (должен быть скрыт в продакшене)
SECRET_KEY = 'django-insecure-tc@235w=y)5-d7@o#5+d1z-d9h6li+eiyy!4u-&9b7o(yff6em'

# SECURITY WARNING: don't run with debug turned on in production!
# Режим отладки (False в продакшене)
DEBUG = True

# Список допустимых хостов
ALLOWED_HOSTS = []


# Application definition

# Список приложений, подключенных к проекту
INSTALLED_APPS = [
    'django.contrib.admin',         # Административная панель Django
    'django.contrib.auth',          # Система аутентификации
    'django.contrib.contenttypes',  # Поддержка типов контента
    'django.contrib.sessions',      # Поддержка сессий
    'django.contrib.messages',      # Система сообщений
    'django.contrib.staticfiles',   # Поддержка статических файлов
    'shop',
    'cart',
    'neuro_assistant',
]

# Промежуточное ПО (middleware) для обработки запросов и ответов
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',         # Настройки безопасности
    'django.contrib.sessions.middleware.SessionMiddleware',  # Поддержка сессий
    'django.middleware.common.CommonMiddleware',             # Общие настройки
    'django.middleware.csrf.CsrfViewMiddleware',             # Защита от CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Аутентификация
    'django.contrib.messages.middleware.MessageMiddleware',  # Поддержка сообщений
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Защита от clickjacking
]

# Основной файл маршрутизации URL
ROOT_URLCONF = 'sushi_delivery_shop.urls'

# Настройки шаблонов
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Шаблонизатор Django
        'DIRS': [],                # Папки с пользовательскими шаблонами
        'APP_DIRS': True,          # Поиск шаблонов в приложениях
        'OPTIONS': {
            'context_processors': [  # Процессоры контекста для передачи данных в шаблоны
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Настройка WSGI для продакшена
WSGI_APPLICATION = 'sushi_delivery_shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Настройки базы данных (SQLite по умолчанию)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',   # Движок базы данных SQLite
        'NAME': BASE_DIR / 'db.sqlite3',          # Путь к файлу базы данных
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# Валидация паролей
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', # Проверка сходства с данными пользователя
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', # Минимальная длина пароля
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', # Защита от распространённых паролей
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', # Проверка на отсутствие чисто числовых паролей
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Настройки языка и часового пояса
LANGUAGE_CODE = 'ru'  # Язык по умолчанию
TIME_ZONE = 'UTC'     # Часовой пояс

# Включить локализацию и поддержку часовых поясов
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки для статических файлов
STATIC_URL = '/static/'                         # URL для статических файлов
STATICFILES_DIRS = (BASE_DIR / 'static', )      # Директория для пользовательских статических файлов
STATIC_ROOT = BASE_DIR / '../static'            # Путь для сбора статических файлов в продакшене

# Настройки для медиа-файлов
MEDIA_ROOT = BASE_DIR / '../media'              # Путь для загрузки медиа-файлов

# Разрешаем окно в окне
X_FRAME_OPTIONS = 'SAMEORIGIN'
