# Generated by Django 5.1.4 on 2024-12-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_popular_products',
            field=models.BooleanField(default=False),
        ),
    ]
