# Generated by Django 5.1.4 on 2024-12-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_on_popular_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='on_popular_products',
            new_name='on_popular',
        ),
    ]
